resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: resource-channelstream-repo
    type: git
    source:
      uri: https://github.com/ergo/channelstream.git
      branch: master

  - name: notify
    type: slack-notification
    source:
      url: ((slack-webhook))

jobs:
  - name: job-run-tests
    plan:
      - get: resource-channelstream-repo
        trigger: true
      - task: run-tests
        file: resource-channelstream-repo/ci/test_task.yml
        ensure:
          put: notify
          params:
            text_file: TEST_RUN_STATUS.txt
