resource_types:
  - name: slack-notification
    type: docker-image
    source:
      repository: cfcommunity/slack-notification-resource

resources:
  - name: resource-channelstream-repo
    type: git
    source:
      uri: https://github.com/ergo/channelstream.git
      branch: master

  - name: notify-slack
    type: slack-notification
    source:
      url: ((slack-webhook))

jobs:
  - name: job-run-tests
    plan:
      - get: resource-channelstream-repo
        trigger: true
      - task: run-tests
        file: resource-channelstream-repo/ci/test_task.yml
        ensure:
          put: notify-slack
          params:
            text_file: notify_message/TEST_RUN_STATUS.txt
            text: |
              The build had a result. Check it out at:
              http://127.0.0.1:8080/teams/$BUILD_TEAM_NAME/pipelines/$BUILD_PIPELINE_NAME/jobs/$BUILD_JOB_NAME/builds/$BUILD_NAME
              or at:
              http://127.0.0.1:8080/builds/$BUILD_ID

              Result: $TEXT_FILE_CONTENT
